FIND_PACKAGE(PkgConfig)
IF(PKG_CONFIG_FOUND)
    PKG_CHECK_MODULES(ttHReco_PKGCONF ttHReco)
ENDIF(PKG_CONFIG_FOUND)

SET(ttHReco_INCLUDE_DIRS ${ttHReco_PKGCONF_INCLUDE_DIRS})
SET(ttHReco_LIBRARY_DIRS ${ttHReco_PKGCONF_LIBRARY_DIRS})
FIND_LIBRARY(ttHReco_LIBRARIES NAMES libttHReco-core.so PATHS ${ttHReco_PKGCONF_LIBRARY_DIRS})
